export default function Head() {
  return (
    <>
      <title>Hello Tailwind</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/logos/panaverse_transparent_small.png" />
    </>
  )
}
